apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
    name: {{ include "weatherapp.fullname" . }}
    namesapce: default
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts: 
      - {{ .Values.gatewayhostname }}
      port: 
        number: {{ .Values.gatewayport }}
        protocol: HTTP
        name: HTTP


